# Generated by Django 5.0.4 on 2024-04-09 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_intent_id", models.CharField(max_length=50, null=True)),
                ("checkout_session_id", models.CharField(max_length=100)),
                (
                    "task",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.task"),
                ),
            ],
        ),
    ]
