# Generated by Django 5.0.4 on 2024-04-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_intent_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
