# Generated by Django 5.0.4 on 2024-06-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supporters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supporter",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars"),
        ),
    ]
