# Generated by Django 5.0.4 on 2024-05-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskOgpImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="task_ogp_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="tasks.task")),
            ],
        ),
    ]
