# Generated by Django 5.0.4 on 2024-04-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "In Progress"),
                    ("D", "Done"),
                    ("F", "Failed"),
                    ("S", "Stopped"),
                ],
                default="I",
                max_length=1,
            ),
        ),
    ]
