# Generated by Django 5.0.4 on 2024-04-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_updated_at_alter_todo_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("S", "Success"), ("F", "Failure")],
                        default="F",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
