# Generated by Django 5.0.4 on 2024-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_regularexecutionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularexecutionlog",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
