# Generated by Django 5.0.4 on 2024-04-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_regularexecutionlog_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "Not Started"),
                    ("I", "In Progress"),
                    ("D", "Done"),
                    ("F", "Failed"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "Not Started"),
                    ("I", "In Progress"),
                    ("D", "Done"),
                    ("F", "Failed"),
                    ("S", "Stopped"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
