# Generated by Django 5.0.4 on 2024-05-04 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="is_resolved",
            field=models.BooleanField(default=False, verbose_name="解決済み"),
        ),
    ]
