# Generated by Django 5.0.4 on 2024-04-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="memo",
            field=models.TextField(blank=True, verbose_name="運営者用メモ欄"),
        ),
    ]
