name: Django Security Scan with Bandit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bandit-security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # プロジェクトに合わせてPythonのバージョンを指定

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./server/django



    - name: Run Bandit Security Scan
      run: bandit -r . # プロジェクトのルートディレクトリから再帰的にスキャン
      working-directory: ./server/django
